### ISSUE TITLE
Querying root record with TXT is not returning origin IP

### ISSUE THREAD

**Issue by ressu** [cunnie/sslip.io#11]
The [homepage](https://sslip.io/#whatismyip) describes a way of getting the origin IP address by running:

```
$ dig @ns-aws.nono.io txt . +short
$
```

Which currently returns blank. Based on the tests in the source code, I was able to get the origin IP by requesting TXT with a domain that matches `ipDomainRE`

```
$ dig @ns-aws.nono.io txt blah.blah.ip +short
"1.2.3.4"
$
```

Based on tests, both forms should work so this might be just a configuration issue somewhere too.

https://github.com/cunnie/sslip.io/blob/30d2c8a67f8a79aaea095a07ebdef5521aa1a79c/bosh-release/src/sslip.io-dns-server/integration_test.go#L116-L123

**Comment by cunnie** [comment]
Hi @ressu,

Good research—thanks. You're right, it's a bug, it doesn't work as documented.

A couple of things: 

1. You're the first person I know of (other than myself) who actually used the feature. If I had a medal, I'd award it to you. 🥇
2. The documentation needs to be updated. I'll mark this feature as "experimental" because I realize that I hadn't fully thought-out the implications when I wrote it. At this moment I'm considering using the `ip.sslip.io` record as record that returns the ip address, i.e.:
```bash
dig @ns-aws.nono.io txt ip.sslip.io. +short
"2601:646:100:69f0:d51c:8371:f14c:bf3b"
```
3. Do you have **any thoughts about the above proposal?**
3. I'd like to introduce more experimental features using the TXT record, e.g. `time.sslip.io`. If you have any ideas let me know. I'm looking for things that are relatively easy to implement & that don't lend themselves to a DNS amplification attack (i.e. I don't want to return a packet that's much larger than the request packet).

**Comment by ressu** [comment]
I think using something like `ip.sslip.io` is a better idea than having the text record available on arbitrary entries. Considering that there are mechanisms that regularly ask for TXT records (SPF for example) it's possible that the TXT record could confuse them. Although most mechanisms have safeguards in place by using prefixes etc special formats.

As for `time.sslip.io` and friends, I can't think of anything immediately useful. I'm assuming that time in this case would be the local time or timezone, which would rely on a IP database, and we all know how reliable those tend to be 😆
