### ISSUE TITLE
can't generate certificates

### ISSUE THREAD

**Issue by joaquinjsb** [cunnie/sslip.io#19]
Hello,
this is what I get from let's encrypt right now

```json{
  "identifier": {
    "type": "dns",
    "value": "192.168.1.13.sslip.io"
  },
  "status": "invalid",
  "expires": "2022-04-20T18:24:21Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "no valid A records found for 192.168.1.13.sslip.io; no valid AAAA records found for 192.168.1.13.sslip.io",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/97928349050/KT5UTA",
      "token": "8RFnhPrdlmv6wyqqvwyxdkGNCc-AYRczIOQ_JjRYrEY",
      "validated": "2022-04-13T18:24:42Z"
    }
  ]
}
```

status on cert-manager

 ` Warning  Failed     19s   cert-manager  Accepting challenge authorization failed: acme: authorization error for 192.168.1.13.sslip.io: 400 urn:ietf:params:acme:error:dns: no valid A records found for 192.168.1.13.sslip.io; no valid AAAA records found for 192.168.1.13.sslip.io`

**Comment by cunnie** [comment]
Hi @joaquinjsb ,

I assume your question is, "why can't I get a Let's Encrypt certificate for 192.168.1.13.sslip.io using the HTTP-01 challenge?"

The short answer is that you can only get certificates for public IP addresses, not private (RFC 1918) addresses. You can't get certificates for 10/8, 192.168/16, or 172.16/12, and you're trying to get a certificate for a private IP address. It won't work.

**Comment by joaquinjsb** [comment]
I get it, wasn't it supposed to be the utility of the service? I mean I tried it on a domain that I own and it worked properly, was it requested by let's encrypt?

**Comment by cunnie** [comment]
> wasn't it supposed to be the utility of the service?

What do you mean by "it" (e.g. "generating certificates for sslip.io hostnames", "mapping hostnames to IP addresses")? And what do you mean by service (e.g. Let's Encrypt or sslip.io)? Please be as precise as possible so that I can properly answer your question.

**Comment by joaquinjsb** [comment]
the generation of ssl certificates for slip.io was requested by them to you to stop issuing certificates ?

when I talk about the utility of the service, I mean that isn't this wildcard domain supposed to help for private IP address too or only for public (and that would explain the missing A DNS record)?

**Comment by cunnie** [comment]
> the generation of ssl certificates for slip.io when using private ip's, was requested to stop the generation by an (let's encrypt) request ?

Let's Encrypt does not issue certificates for hostnames with private IP addresses using the HTTP-01 challenge. You're using the HTTP-01 challenge, and your hostname resolves to a private IP address. You'll never get a certificate.

> this wildcard domain

Please clarify: do you mean "wildcard" in the sense of a [Wildcard DNS record](https://en.wikipedia.org/wiki/Wildcard_DNS_record). Because wildcard DNS records have a "*" in them, and your hostname (192.168.1.13.sslip.io) does not have a "*" in it. Also, Let's Encrypt won't issue wildcard certs using the HTTP-01 challenge, only the DNS-01 challenge.

> and that would explain the missing A DNS record

You're not missing DNS A record, you're missing a _valid_ DNS A record. In other words, you're missing a public IP address.
