### ISSUE TITLE
req: Official/Updated docker images

### ISSUE THREAD

**Issue by dekimsey** [cunnie/sslip.io#21]
Are there official docker images?

I noticed there is a user, "cunnie" in Docker Hub that appears to have released [sslip.io builds](https://hub.docker.com/u/cunnie). But they are out of date (latest is 2.2.2), and the source Dockerfiles aren't linked so the providence of of the images isn't clear to me.

Two asks then:
1) Add or fix the CI to build/publish the Dockerfiles.
2) Add a link to the appropriate docker.hub repositories in the Readme.

Thank you!

**Comment by cunnie** [comment]
Hi @dekimsey !

> Are there official docker images?

Yes, you found them! https://hub.docker.com/r/cunnie/sslip.io-dns-server

> I noticed there is a user, "cunnie" in Docker Hub

That's me!

> But they are out of date (latest is 2.2.2), and the source Dockerfiles aren't linked so it's not clear regarding the provenance of the images are

I'll try to update the docs. It might take me a couple of days.

> Add or fix the CI to build/publish the Dockerfiles.

Done! It should have built a new image. The way it's configured the new image will sometimes be "too" new, with half-implemented features. Maybe I'll try to re-engineer it so that the Docker image always maps to the latest GitHub release, but that'll take a couple of hours.

**Comment by cunnie** [comment]
> Are there official docker images?

Not really, but I'll try to make some.

> noticed there is a user, "cunnie" in Docker Hub that appears to have released [sslip.io builds](https://hub.docker.com/u/cunnie). But they are out of date...

Yup, that's my Docker account, and <https://hub.docker.com/r/cunnie/sslip.io-dns-server> is a legitimate build.

> Add or fix the CI to build/publish the Dockerfiles

Here's the existing, inadequate CI: <https://ci.nono.io/teams/main/pipelines/dockerfiles/jobs/build-and-push-sslip.io-dns-server/builds/4>. It needs to be fixed to be in lockstep with releases rather than tracking HEAD.

> Add a link to the appropriate docker.hub repositories in the Readme

Yup, when I get the Docker publishing done I'll put in a link in the README.

Thanks for showing such deep interest in sslip.io code! You made my day.

**Comment by cunnie** [comment]
Closing. Docker images are published & documented.

**Comment by cunnie** [comment]
@dekimsey : heads-up: The newest Docker image (v2.6.2+) should be invoked differently, without `/usr/sbin/sslip.io-dns-server` when args are passed:

```diff
 docker run \
   -it \
   --rm \
   -p 53:53/udp \
-    cunnie/sslip.io-dns-server \
       /usr/sbin/sslip.io-dns-server \
       -nameservers jammy.nono.io \
       -addresses jammy.nono.io=10.9.9.114,jammy.nono.io=2601:646:100:69f0:0:ff:fe00:72

```
