### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by BrianRossmajer** [cunnie/sslip.io#28]
I was thinking on working on a feature that I think would be useful for me; just seeking advice/concerns/approval... so just starting a conversation before I dive in.

A round-robin sslip would come in handy for me for my little docker swarm.  So I've been thinking about augmenting the parser to accept something like s4e7 for the last component, and either return a random address in that range, or return all the answers [4,5,6,7](preferably or selectably in random order)

I think that should be compatible with both the dot- and dash-formatted embedded types, and allow for future expansion like multiple ranges, non-contiguous IPs, that sort of thing.  No idea what to do for IPv6 though.

**Comment by cunnie** [comment]
@BrianRossmajer : I'm not sure I understand. Please provide some examples, e.g.: "looking up  s1e5.127.0.0.1.sslip.io returns 5 A records, 127.0.0.1, 127.0.0.2, 127.0.0.3, 127.0.0.4, 127.0.0.5"

**Comment by BrianRossmajer** [comment]
Oh, good point - I see I didn't express that very well.  I was thinking that looking up 127.0.0.s1e5.sslip.io would return the five A records you indicated, as would www-127-0-0-s1e5.sslip.io

I think this would not interfere with any of the functionality, including obtaining wildcard ssl certs to resolve names like www-192-168-0-s10e12.52-187-42-s158e159.xip.example.com if one had redundant dns servers at 52.187.42.158 and 52.187.42.159, both running the sslip code and configured to be authoritative for _acme-challenge.52-187-42-s158e159.xip.example.com ... Then both servers would return the three A records 192.168.0.10, 192.168.0.11 and 192.168.0.12

**Comment by cunnie** [comment]
Thanks for the explanation!

I think I'm going to say no to the extension you suggest: not because it's a bad suggestion—it's a great suggestion—but because sslip.io isn't suitable. It's stiff; the code has to be done by hand. The IPv6 regex is already a monster!

A better way to have written the sslip.io DNS server would have been to use https://github.com/miekg/dns (a Golang DNS backend) or what the nip.io folks did: use PowerDNS with a custom Python backend. Much more flexibility.

I'm sorry to say no, but feel free to fork. And, of course, good luck.

**Comment by BrianRossmajer** [comment]
Thanks!  Glad I asked!  :-)
