### ISSUE TITLE
why is this called *ssl* ip

### ISSUE THREAD

**Issue by kumavis** [cunnie/sslip.io#31]
unclear what the role of "ssl" is in the name as the service doesnt seem to do anything ssl specific

**Comment by cunnie** [comment]
Hi @kumavis 

> unclear what the role of "ssl" is in the name as the service doesnt seem to do anything ssl specific

You're right—it doesn't do anything SSL-specific, but it did in its first incarnation (2015?): we had a certificate and private key that we released to the public for `*.sslip.io` so that developers could use a valid certificate for, say, 127.0.0.1.sslip.io, but once Comodo (now Sectigo) got wind of that they revoked our key within 24 hours.

Even though the "ssl" in the name no longer made sense, we never bothered to change it.

**Comment by kumavis** [comment]
thanks/

I was wondering if you could do a dns-auth cert as well but http-auth seems much easier

**Comment by cunnie** [comment]
> I was wondering if you could do a dns-auth cert as well but http-auth seems much easier

*Not easily*. #24 is a good example of an ongoing discussion to address this.
