### ISSUE TITLE
No idea why you blocked my site... its just an api for a minecraft community I run on a minecraft server

### ISSUE THREAD

**Issue by JoshTheDeveloperr** [cunnie/sslip.io#78]
No idea why you blocked my site... its just an api for a minecraft community I run on a minecraft server

**Comment by JoshTheDeveloperr** [comment]
I added the  X-Robots-Tag: noindex to my header nonetheless.

**Comment by JoshTheDeveloperr** [comment]
Just realized I didn't include the link http://ns8k444.23.137.104.229.sslip.io

**Comment by cunnie** [comment]
Hey @JoshTheDeveloperr apologies for the inconvenience — I've unblocked your site; the unblocking should propagate over the next few hours.

Just to let you know, I'm not happy about the blocking-thing either, but it's been forced upon us because many people (over 700 at last count) abuse the sslip.io service to phish & scam & unauthorized mirror.

@Morty-Feldman has been spearheading an effort to preemptively block those sites, and has done a fantastic job. The reason your site got caught (according to our notes) was not only the lack of a "noindex" but also that your site was mirroring a legitimate site, <https://reviewscaribbean.com/>. Don't worry about the mirroring — as long as your site's not indexed you can mirror as much as you want.

Have a great day!

**Comment by JoshTheDeveloperr** [comment]
Oh ok. That's quite funny as I used to host reviewscaribbean.com on the same server but I moved it a few weeks ago haha.

**Comment by cunnie** [comment]
You used to host reviewscaribbean?! That's really funny.
